import type {Metadata} from "next";
import {Inter, Exo_2} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner"

const interSans = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin"],
});
const exo2 = Inter({
    variable: "--font-exo",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html style={{scrollBehavior:'smooth'}} lang="en">
        <body
            className={`${interSans.variable} ${exo2.variable} antialiased`}
        >
        {children}
        <Toaster/>
        </body>
        </html>
    );
}
